### PR TITLE
Change default intercept distribution to CosineSimilarity(d+2)

### PR DESCRIPTION
**Pull request by jgosmann**
My first NEP. Is there anything in particular that should go into the PR description?

Note that I'm not fully convinced that we should change the default intercept distribution, but I think we should discuss this and make a documented decision.

### CODE REVIEW

**Comment by tbekolay** [comment]
Haven't done many of these yet, so not sure what's helpful in the PR description :) I added an agenda item to the next dev meeting to talk about how we want to go about reviewing these... seems like they should all be discussed at dev meetings at the minimum.

I'll save my philosophical thoughts for the discussion, but on a technical note, it would be possible to make this change without placeholders, deferrables, or a helper function. Right now `CosineSimilarity` requires you to pass in the dimensionality in the constructor so that the dimensionality of the distribution can vary independently of the dimensionality of the sample produced in the `sample` method. We can make a subclass of `CosineSimilarity` that does not require the dimensionality on construction, and instead uses the dimensionality passed to `sample` to determine the dimensionality used for the distribution. In other words, in this subclass we would make the distribution's dimensionality depend on the dimensionality passed to `sample`.

**Comment by jgosmann** [comment]
> We can make a subclass of CosineSimilarity that does not require the dimensionality on construction, and instead uses the dimensionality passed to sample to determine the dimensionality used for the distribution

I don't think so. Intercepts are 1-dimensional (no matter the what the ensemble dimensionality is) and thus either `d=None` or `d=1` will be passed to the `sample` function.

**Comment by tbekolay** [comment]
> Intercepts are 1-dimensional (no matter the what the ensemble dimensionality is) and thus either d=None or d=1 will be passed to the sample function.

Ah my mistake, I was thinking about encoders for some reason.

**Comment by jgosmann** [comment]
In the context of the discussion about `represent_identity` in nengo/nengo_spa#4 it ocurred to me that it might be useful to not only have the intercept distribution dependent on the ensemble dimensionality, but to be able to have it dependent on the encoders. I think that would give full flexibility about how neurons cover the representational space (or in other words allows to cover weirdly shaped representational spaces that are non-isotropic). Of course doing something like this is pretty niche, though a less general case of different radii for different dimensions has been discussed in nengo/nengo#257 and #6 and has been rejected.

**Comment by tbekolay** [comment]
We also discussed this NEP at the dev meeting on June 19, 2017. Generally, we are in favour of making this change, but have not yet come to a consensus on a good mechanism for implementing this change (deferrables, network transforms, etc). Like #12, this one is therefore on hold until such a mechanism is agreed upon. Head to #12 to discuss that.

**Comment by arvoelke** [comment]
Is there any progress on this proposal? The evidence in @jgosmann's [thesis](http://compneuro.uwaterloo.ca/publications/gosmann2018-1.html) is quite compelling. From a theoretical perspective, it seems like the right thing to be doing assuming the function is a low-degree monomial of the semantic pointer (e.g., a communication channel).

**Comment by tbekolay** [comment]
Migrated to a Google Doc.

**Comment by jgosmann** [comment]
Do I have access to that Google Doc?

**Comment by tbekolay** [comment]
> Do I have access to that Google Doc?

We're switching from the enhancement proposals system to a more informal internal ABR process to speed up development of big projects like those described in these enhancement proposals. We're still happy to get external contributions and will continue to develop in public spaces (i.e., public github issues, PRs etc) but we're doing the planning, prioritizing, and scheduling internally.

**Comment by jgosmann** [comment]
I see ... the reason I'm asking is that I would be interested in following the progress on this particular NEP.

**Comment by tbekolay** [comment]
We don't have any plans to work on this at the moment, but we can let you know if we add it to a sprint and open a WIP PR earlier than we normally would. Is that enough to follow along or do you want to discuss it on the dev section of the forum or something like that?

**Comment by jgosmann** [comment]
I think that should be sufficient. :)

**Pull request closed without merging**
